/* SQL CONSTRAINTS
SQL CONSTRAINTS ARE USED TO SPECIFY ANY RULES  FOR THE RECORDSS INT A TABLE.
THEY CAN BE USED TO LIMIT THE TYPE OF DATA THAT CAN GO INTO A TABLE.
IT ENSURES THE ACCURACY AND RELIABLITY OF THE RECORDS IN THE TABLE, AND
IF THERE IS ANY VIOLATION BETWEEN THE CONSTRAINT ANT THE RECORD ACTION, 
THE ACTION IS ABSORBED. CONSTRAINTS CAN BE column LEVEL OR TABLE LEVEL.
COLUMN LEVEL CONSTRAINTS APPLY TO A COLUMN AND TABLE LEVEL APPLIES TO WHOLE TABLE.

> NOT NULL
>UNIQUE
>PRIMARY KEY
>FOREIGN KEY
>CHECK
>DEFAULT
>INDEX

*/
CREATE TABLE STUDENT (
	ID INT NOT NULL,
    FIRST_NAME VARCHAR(25) NOT NULL,
    LAST_NAME VARCHAR(25) NOT NULL,
    AGE INT
);

DESC STUDENT;
ALTER TABLE STUDENT MODIFY AGE INT NOT NULL;
#UNIQUE; CAN CALL IT IN MULTIPLE WAYS

CREATE TABLE PERSON(
	ID INT UNIQUE NOT NULL,  #	ID by default turns to be primary key because its not null and unique
    NAME VARCHAR(25) NOT NULL,
    AGE INT NOT NULL
);

INSERT INTO PERSON VALUES(1, 'KANISHK', 23);
SELECT * FROM PERSON;
INSERT INTO PERSON VALUES(1,'MADHAV', 18);
ALTER TABLE PERSON ADD UNIQUE(NAME);
CREATE TABLE TEACHER(
	ID INT NOT NULL,
    NAME VARCHAR(25) NOT NULL,
    SUBJECT VARCHAR(25) NOT NULL,
    unique(ID)
);

#ADD MULTI CONSTRAINT
ALTER TABLE PERSON ADD CONSTRAINT UC_P UNIQUE(AGE,NAME);

# DROP CONSTRAINT
ALTER TABLE PERSON DROP INDEX UC_P;

DESC TEACHER;
DESC PERSON;


#PRIMARY KEY
CREATE TABLE PERSON1(
	ID INT NOT NULL,
    FIRST_NAME VARCHAR(22) NOT NULL,
    LAST_NAME VARCHAR(22),
    AGE INT,
    CONSTRAINT PK_P PRIMARY KEY(ID, LAST_NAME)
);

ALTER TABLE PERSON1 DROP PRIMARY KEY;

DESC PERSON1;
